import React, { useState, useMemo } from 'react';
import {
  HelpCircle,
  Search,
  BookOpen,
  ShieldCheck,
  Scale,
  FileText,
  ChevronDown,
  ChevronUp,
  Layers,
  ArrowRight,
} from 'lucide-react';
import { WorkspaceTab } from '@/types/reconciliation';

interface HelpTabProps {
  onNavigateTab: (tab: WorkspaceTab) => void;
  onStartTour: () => void;
}

interface FAQItem {
  id: string;
  category: 'Concepts' | 'Scoring' | 'Safety' | 'Metrics' | 'AI';
  question: string;
  answer: string;
  targetTab?: WorkspaceTab;
}

const FAQ_DATABASE: FAQItem[] = [
  {
    id: 'what-is-3way',
    category: 'Concepts',
    question: 'What is 3-way financial reconciliation in Razorpay?',
    answer:
      '3-way reconciliation verifies three financial legs: (1) Captured customer orders in the merchant ledger, (2) Nodal gateway settlement batches with 2.0%-3.5% fee + 18% GST deductions, and (3) Actual credit entries on the merchant bank account statement matching via bank UTR.',
    targetTab: 'control_center',
  },
  {
    id: 'why-amounts-differ',
    category: 'Concepts',
    question: 'Why do settled amounts differ from payment gross amounts?',
    answer:
      'Payment gateways deduct Merchant Discount Rate (MDR) fees (typically 2.0% for standard cards up to 3.5% for corporate cards) plus 18% GST on the fee portion. For example, a ₹5,000 transaction with 2% MDR has ₹100 fee + ₹18 GST = ₹118 total fee, settling exactly ₹4,882.00 (488,200 paise).',
    targetTab: 'reconciliation',
  },
  {
    id: 'how-scoring-works',
    category: 'Scoring',
    question: 'How does the 4-factor scoring engine work?',
    answer:
      'Every candidate match is evaluated across 4 deterministic factors totaling 100 points: Reference Match (40 pts), Amount Compatibility (35 pts: 20 for expected net + 15 for bank credit), Date Proximity (15 pts for T+0 to T+3), and UTR / Description Overlap (10 pts).',
    targetTab: 'methodology',
  },
  {
    id: 'auto-vs-review',
    category: 'Scoring',
    question: 'What separates Auto-Reconciled matches from Human Review cases?',
    answer:
      'Records with confidence score >= 85% AND clean matching type are safely auto-reconciled. Any record with score 50%-84% OR an anomaly (such as date skew, fee rate variance, or ambiguous amount) is routed to the human reviewer queue with 100% explainability.',
    targetTab: 'reconciliation',
  },
  {
    id: 'financial-exposure',
    category: 'Safety',
    question: 'How is Financial Exposure calculated?',
    answer:
      'Financial exposure measures the exact rupee value at risk for unresolved or missing legs. For missing bank credits, exposure is the full net settled amount. For fee discrepancies, exposure is the delta between expected and actual fee deductions.',
    targetTab: 'exceptions',
  },
  {
    id: 'immutable-baseline',
    category: 'Safety',
    question: 'Are baseline benchmark metrics immutable when human reviewers act?',
    answer:
      'Yes. When a finance controller Approves, Rejects, or Flags a transaction, operational counters update live, but the baseline algorithmic ground-truth benchmark remains strictly immutable. This prevents human actions from masking engine classification defects.',
    targetTab: 'evaluation',
  },
  {
    id: 'gemini-boundary',
    category: 'AI',
    question: 'What is Gemini AI’s operational boundary?',
    answer:
      'Gemini 2.5 Flash operates strictly as an advisory copilot via server-side route. It cannot modify transaction amounts, alter confidence scores, approve records, or move funds. When offline or without API keys, a deterministic fallback activates with explicit UI disclosure.',
    targetTab: 'exceptions',
  },
  {
    id: 'metric-separation',
    category: 'Metrics',
    question: 'Why are Proposed-Pair and Auto-Resolution metrics separated?',
    answer:
      'Combining all predictions into a single aggregate obscures whether the engine made correct ID pairings versus whether it made safe auto-resolution decisions. ShaRecon AI reports Proposed-Pair Precision/Recall, Auto-Resolution Precision/Recall, Review-Routing Accuracy, and False-Positive Monetary Exposure separately.',
    targetTab: 'evaluation',
  },
  {
    id: 'integer-paise',
    category: 'Safety',
    question: 'Why does ShaRecon AI use integer-paise arithmetic?',
    answer:
      'Standard JavaScript floating-point numbers introduce IEEE 754 precision drift (e.g. 0.1 + 0.2 = 0.30000000000000004). Enforcing 1 INR = 100 integer paise guarantees zero rounding error across ledger additions, fee deductions, and currency deltas.',
    targetTab: 'methodology',
  },
];

const GLOSSARY_TERMS = [
  {
    term: 'UTR (Unique Transaction Reference)',
    definition: 'A 16-to-22 character alphanumeric identifier generated by Indian banking systems (NEFT/RTGS/IMPS) that uniquely confirms bank account credit.',
  },
  {
    term: 'Nodal / Escrow Account',
    definition: 'A special RBI-mandated intermediary bank account held by payment aggregators (like Razorpay) where customer funds sit before settlement to merchant accounts.',
  },
  {
    term: 'MDR (Merchant Discount Rate)',
    definition: 'The fee percentage charged by payment aggregators per transaction, ranging from 2.0% (standard cards/UPI) to 3.5% (corporate/international).',
  },
  {
    term: 'GST on MDR (18%)',
    definition: 'Indian Goods and Services Tax applied exclusively to the gateway fee component, deducted alongside MDR prior to bank payout.',
  },
  {
    term: 'Integer-Paise Math',
    definition: 'Storing monetary values as integer sub-units (₹1 = 100 paise) to prevent floating-point binary rounding errors in financial computations.',
  },
  {
    term: '1-to-1 Collision Lock',
    definition: 'A deterministic constraint solver ensuring no settlement line or bank transaction is assigned to more than one customer payment.',
  },
];

export const HelpTab: React.FC<HelpTabProps> = ({ onNavigateTab, onStartTour }) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState<string>('ALL');
  const [expandedFaqId, setExpandedFaqId] = useState<string | null>('what-is-3way');

  const filteredFaqs = useMemo(() => {
    return FAQ_DATABASE.filter((faq) => {
      if (activeCategory !== 'ALL' && faq.category !== activeCategory) return false;
      if (!searchQuery) return true;
      const q = searchQuery.toLowerCase();
      return (
        faq.question.toLowerCase().includes(q) ||
        faq.answer.toLowerCase().includes(q) ||
        faq.category.toLowerCase().includes(q)
      );
    });
  }, [searchQuery, activeCategory]);

  return (
    <div className="space-y-6 max-w-5xl">
      {/* Header with Guided Tour CTA */}
      <div className="elevated-card p-6 bg-gradient-to-r from-[#090d16] via-[#111620] to-[#090d16] border border-white/12 text-[#f7f8fc] flex flex-wrap items-center justify-between gap-4 shadow-2xl">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-[#7168ff] text-xs font-bold uppercase tracking-wider font-mono">
            <BookOpen className="w-4 h-4 text-[#7168ff]" />
            <span>How ShaRecon AI Works</span>
          </div>
          <h2 className="text-xl font-extrabold tracking-tight text-[#f7f8fc] font-mono">
            ShaRecon AI Architecture &amp; Reviewer Guide
          </h2>
          <p className="text-xs text-[#a7afc0] max-w-xl leading-relaxed font-sans">
            Understand the 3-way reconciliation lifecycle, deterministic 4-factor scoring graph, honest evaluation metrics, and non-destructive AI boundaries.
          </p>
        </div>

        <button
          onClick={onStartTour}
          className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-[#7168ff] to-[#5687ff] hover:from-[#5d53ea] hover:to-[#4375ea] text-white text-xs font-semibold flex items-center gap-2 transition-all shadow-[0_0_15px_rgba(113,104,255,0.4)] cursor-pointer"
        >
          <span>Start 5-Minute Guided Tour</span>
          <ArrowRight className="w-4 h-4" />
        </button>
      </div>

      {/* 3-Source Reconciliation Visual Explanation */}
      <div className="elevated-card p-6 space-y-4 bg-[#111620] border-white/10">
        <h3 className="text-base font-bold text-[#f7f8fc] flex items-center gap-2 font-mono">
          <Layers className="w-5 h-5 text-[#7168ff]" />
          <span>The 3-Way Reconciliation Lifecycle</span>
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
          <div className="inset-panel p-4.5 rounded-xl space-y-2 border-t-2 border-t-[#7168ff] bg-[#0c101a] border-white/10">
            <div className="flex items-center justify-between">
              <span className="font-bold text-[#f7f8fc] font-mono">Leg 1: Merchant Ledger</span>
              <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-[#7168ff]/20 text-[#c4b5fd] font-mono border border-[#7168ff]/30">ORDER</span>
            </div>
            <p className="text-[#a7afc0] leading-relaxed font-sans">
              Customer payment captured via Razorpay checkout. Records Gross Amount (e.g. ₹5,000.00), Payment ID (<code className="text-[#c4b5fd]">pay_0001</code>), Order Ref (<code className="text-[#c4b5fd]">order_0001</code>), and timestamp.
            </p>
          </div>

          <div className="inset-panel p-4.5 rounded-xl space-y-2 border-t-2 border-t-[#f5b942] bg-[#0c101a] border-white/10">
            <div className="flex items-center justify-between">
              <span className="font-bold text-[#f7f8fc] font-mono">Leg 2: Nodal Settlement</span>
              <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-[#f5b942]/20 text-[#f5b942] font-mono border border-[#f5b942]/30">GATEWAY</span>
            </div>
            <p className="text-[#a7afc0] leading-relaxed font-sans">
              Razorpay settles captured funds in payout batches deducting 2.0%-3.5% MDR + 18% GST on fee. Records Net Amount (e.g. ₹4,882.00), Settlement ID, and UTR.
            </p>
          </div>

          <div className="inset-panel p-4.5 rounded-xl space-y-2 border-t-2 border-t-[#2dd4bf] bg-[#0c101a] border-white/10">
            <div className="flex items-center justify-between">
              <span className="font-bold text-[#f7f8fc] font-mono">Leg 3: Bank Account</span>
              <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-[#2dd4bf]/20 text-[#2dd4bf] font-mono border border-[#2dd4bf]/30">STATEMENT</span>
            </div>
            <p className="text-[#a7afc0] leading-relaxed font-sans">
              Merchant bank account credits arriving after T+1/T+2 clearing delay. Records exact credit amount, bank statement UTR (<code className="text-[#2dd4bf]">RBIP100...</code>), and date.
            </p>
          </div>
        </div>
      </div>

      {/* 4-Factor Scoring Breakdown */}
      <div className="elevated-card p-6 space-y-4 bg-[#111620] border-white/10">
        <h3 className="text-base font-bold text-[#f7f8fc] flex items-center gap-2 font-mono">
          <Scale className="w-5 h-5 text-[#7168ff]" />
          <span>Deterministic 4-Factor Confidence Scoring (0 - 100 Points)</span>
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3.5 text-xs">
          <div className="inset-panel p-4 rounded-xl space-y-1.5 bg-[#0c101a] border-white/10">
            <div className="flex items-center justify-between">
              <span className="font-bold text-[#f7f8fc]">1. Reference Match</span>
              <span className="font-mono font-bold text-[#7168ff]">40 Pts</span>
            </div>
            <p className="text-[#a7afc0] text-[11px] leading-relaxed font-sans">
              Exact payment ID (<code className="text-[#c4b5fd]">40 pts</code>), order reference (<code className="text-[#c4b5fd]">30 pts</code>), or sanitized token substring (<code className="text-[#c4b5fd]">20 pts</code>).
            </p>
          </div>

          <div className="inset-panel p-4 rounded-xl space-y-1.5 bg-[#0c101a] border-white/10">
            <div className="flex items-center justify-between">
              <span className="font-bold text-[#f7f8fc]">2. Amount Match</span>
              <span className="font-mono font-bold text-[#2dd4bf]">35 Pts</span>
            </div>
            <p className="text-[#a7afc0] text-[11px] leading-relaxed font-sans">
              Net settled vs expected MDR+GST net (<code className="text-[#2dd4bf]">20 pts</code>) + Bank credit vs settled (<code className="text-[#2dd4bf]">15 pts</code>) in exact paise.
            </p>
          </div>

          <div className="inset-panel p-4 rounded-xl space-y-1.5 bg-[#0c101a] border-white/10">
            <div className="flex items-center justify-between">
              <span className="font-bold text-[#f7f8fc]">3. Date Proximity</span>
              <span className="font-mono font-bold text-[#f5b942]">15 Pts</span>
            </div>
            <p className="text-[#a7afc0] text-[11px] leading-relaxed font-sans">
              T+0 to T+1 calendar proximity (<code className="text-[#f5b942]">15 pts</code>), T+2 (<code className="text-[#f5b942]">10 pts</code>), T+3 (<code className="text-[#f5b942]">5 pts</code>). Negative delta penalized.
            </p>
          </div>

          <div className="inset-panel p-4 rounded-xl space-y-1.5 bg-[#0c101a] border-white/10">
            <div className="flex items-center justify-between">
              <span className="font-bold text-[#f7f8fc]">4. UTR &amp; Description</span>
              <span className="font-mono font-bold text-[#a78bfa]">10 Pts</span>
            </div>
            <p className="text-[#a7afc0] text-[11px] leading-relaxed font-sans">
              Alphanumeric UTR format validation (<code className="text-[#a78bfa]">5 pts</code>) + statement description token overlap (<code className="text-[#a78bfa]">5 pts</code>).
            </p>
          </div>
        </div>
      </div>

      {/* Searchable FAQ Section */}
      <div className="elevated-card p-6 space-y-4 bg-[#111620] border-white/10">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h3 className="text-base font-bold text-[#f7f8fc] flex items-center gap-2 font-mono">
              <HelpCircle className="w-5 h-5 text-[#7168ff]" />
              <span>Frequently Asked Questions</span>
            </h3>
            <p className="text-xs text-[#a7afc0] mt-0.5 font-sans">
              Clear technical explanations for hackathon evaluators and finance controllers.
            </p>
          </div>

          {/* Search Box */}
          <div className="relative min-w-[240px]">
            <Search className="w-4 h-4 text-[#7d879b] absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search concepts, formulas..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-3 py-1.5 bg-[#0c101a] border border-white/10 rounded-xl text-xs text-[#f7f8fc] placeholder:text-[#7d879b] focus:outline-hidden focus:ring-1 focus:ring-[#7168ff] transition-colors"
            />
          </div>
        </div>

        {/* Category Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1 text-xs">
          {(['ALL', 'Concepts', 'Scoring', 'Safety', 'Metrics', 'AI'] as const).map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-3 py-1.5 rounded-lg font-semibold transition-all shrink-0 cursor-pointer ${
                activeCategory === cat
                  ? 'bg-[#7168ff] text-white shadow-[0_0_10px_rgba(113,104,255,0.4)]'
                  : 'bg-[#0c101a] text-[#a7afc0] hover:bg-white/5 hover:text-white border border-white/10'
              }`}
            >
              {cat === 'ALL' ? 'All Questions' : cat}
            </button>
          ))}
        </div>

        {/* Accordion FAQ List */}
        <div className="space-y-2.5 pt-2">
          {filteredFaqs.map((faq) => {
            const isExpanded = expandedFaqId === faq.id;

            return (
              <div
                key={faq.id}
                className="border border-white/10 rounded-xl overflow-hidden transition-colors bg-[#0c101a]"
              >
                <button
                  onClick={() => setExpandedFaqId(isExpanded ? null : faq.id)}
                  className="w-full px-4 py-3 text-left flex items-center justify-between gap-3 hover:bg-white/5 transition-colors cursor-pointer"
                  aria-expanded={isExpanded}
                >
                  <span className="text-xs sm:text-sm font-bold text-[#f7f8fc]">
                    {faq.question}
                  </span>
                  <div className="flex items-center gap-2 shrink-0">
                    <span className="text-[10px] font-semibold uppercase px-2 py-0.5 rounded bg-white/10 text-[#a7afc0] font-mono">
                      {faq.category}
                    </span>
                    {isExpanded ? (
                      <ChevronUp className="w-4 h-4 text-[#7d879b]" />
                    ) : (
                      <ChevronDown className="w-4 h-4 text-[#7d879b]" />
                    )}
                  </div>
                </button>

                {isExpanded && (
                  <div className="px-4 pb-3.5 pt-1 text-xs text-[#a7afc0] bg-[#070a10] border-t border-white/10 space-y-2 leading-relaxed font-sans">
                    <p>{faq.answer}</p>
                    {faq.targetTab && (
                      <button
                        onClick={() => onNavigateTab(faq.targetTab!)}
                        className="text-xs text-[#7168ff] hover:text-[#5687ff] font-semibold hover:underline inline-flex items-center gap-1 cursor-pointer pt-1"
                      >
                        <span>Open related workspace</span>
                        <ArrowRight className="w-3 h-3" />
                      </button>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Financial Terms Glossary */}
      <div className="elevated-card p-6 space-y-4 bg-[#111620] border-white/10">
        <h3 className="text-base font-bold text-[#f7f8fc] flex items-center gap-2 font-mono">
          <FileText className="w-5 h-5 text-[#2dd4bf]" />
          <span>Fintech &amp; Reconciliation Glossary</span>
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5 text-xs">
          {GLOSSARY_TERMS.map((term) => (
            <div
              key={term.term}
              className="inset-panel p-4 rounded-xl space-y-1 bg-[#0c101a] border-white/10"
            >
              <span className="font-bold text-[#f7f8fc] font-mono text-[11px] block text-[#c4b5fd]">
                {term.term}
              </span>
              <p className="text-[#a7afc0] leading-relaxed font-sans">{term.definition}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Non-Negotiable Safety Disclosures */}
      <div className="bg-[#f5b942]/10 border border-[#f5b942]/30 rounded-2xl p-5 shadow-xs text-xs text-[#fde68a] space-y-2">
        <div className="flex items-center gap-2 font-bold text-[#f5b942]">
          <ShieldCheck className="w-4 h-4 text-[#f5b942] shrink-0" />
          <span>Buildathon Prototype Disclosures &amp; Safety Boundaries</span>
        </div>
        <ul className="list-disc pl-5 space-y-1 text-[#fde68a]/90 leading-relaxed font-sans">
          <li><strong>Synthetic Simulation</strong>: All records, UTRs, and settlements are generated deterministically to model Razorpay fee rules and banking delays.</li>
          <li><strong>No Real Money Movement</strong>: ShaRecon AI is an analytical reconciliation controller and does not initiate bank transfers or payment gateway refunds.</li>
          <li><strong>Advisory AI</strong>: Gemini 2.5 Flash functions strictly as an advisory copilot; core reconciliation logic operates 100% deterministically without external LLM dependencies.</li>
        </ul>
      </div>
    </div>
  );
};
