import React, { useState, useMemo } from 'react';
import {
  HelpCircle,
  Search,
  BookOpen,
  ShieldCheck,
  Scale,
  FileText,
  ChevronDown,
  ChevronUp,
  Layers,
  ArrowRight,
} from 'lucide-react';
import { WorkspaceTab } from '@/types/reconciliation';

interface HelpTabProps {
  onNavigateTab: (tab: WorkspaceTab) => void;
  onStartTour: () => void;
}

interface FAQItem {
  id: string;
  category: 'Concepts' | 'Scoring' | 'Safety' | 'Metrics' | 'AI';
  question: string;
  answer: string;
  targetTab?: WorkspaceTab;
}

const FAQ_DATABASE: FAQItem[] = [
  {
    id: 'what-is-3way',
    category: 'Concepts',
    question: 'What is 3-way financial reconciliation in Razorpay?',
    answer:
      '3-way reconciliation verifies three financial legs: (1) Captured customer orders in the merchant ledger, (2) Nodal gateway settlement batches with 2.0%-3.5% fee + 18% GST deductions, and (3) Actual credit entries on the merchant bank account statement matching via bank UTR.',
    targetTab: 'control_center',
  },
  {
    id: 'why-amounts-differ',
    category: 'Concepts',
    question: 'Why do settled amounts differ from payment gross amounts?',
    answer:
      'Payment gateways deduct Merchant Discount Rate (MDR) fees (typically 2.0% for standard cards up to 3.5% for corporate cards) plus 18% GST on the fee portion. For example, a ₹5,000 transaction with 2% MDR has ₹100 fee + ₹18 GST = ₹118 total fee, settling exactly ₹4,882.00 (488,200 paise).',
    targetTab: 'reconciliation',
  },
  {
    id: 'how-scoring-works',
    category: 'Scoring',
    question: 'How does the 4-factor scoring engine work?',
    answer:
      'Every candidate match is evaluated across 4 deterministic factors totaling 100 points: Reference Match (40 pts), Amount Compatibility (35 pts: 20 for expected net + 15 for bank credit), Date Proximity (15 pts for T+0 to T+3), and UTR / Description Overlap (10 pts).',
    targetTab: 'methodology',
  },
  {
    id: 'auto-vs-review',
    category: 'Scoring',
    question: 'What separates Auto-Reconciled matches from Human Review cases?',
    answer:
      'Records with confidence score >= 85% AND clean matching type are safely auto-reconciled. Any record with score 50%-84% OR an anomaly (such as date skew, fee rate variance, or ambiguous amount) is routed to the human reviewer queue with 100% explainability.',
    targetTab: 'reconciliation',
  },
  {
    id: 'financial-exposure',
    category: 'Safety',
    question: 'How is Financial Exposure calculated?',
    answer:
      'Financial exposure measures the exact rupee value at risk for unresolved or missing legs. For missing bank credits, exposure is the full net settled amount. For fee discrepancies, exposure is the delta between expected and actual fee deductions.',
    targetTab: 'exceptions',
  },
  {
    id: 'immutable-baseline',
    category: 'Safety',
    question: 'Are baseline benchmark metrics immutable when human reviewers act?',
    answer:
      'Yes. When a finance controller Approves, Rejects, or Flags a transaction, operational counters update live, but the baseline algorithmic ground-truth benchmark remains strictly immutable. This prevents human actions from masking engine classification defects.',
    targetTab: 'evaluation',
  },
  {
    id: 'gemini-boundary',
    category: 'AI',
    question: 'What is Gemini AI’s operational boundary?',
    answer:
      'Gemini 2.5 Flash operates strictly as an advisory copilot via server-side route. It cannot modify transaction amounts, alter confidence scores, approve records, or move funds. When offline or without API keys, a deterministic fallback activates with explicit UI disclosure.',
    targetTab: 'exceptions',
  },
  {
    id: 'metric-separation',
    category: 'Metrics',
    question: 'Why are Proposed-Pair and Auto-Resolution metrics separated?',
    answer:
      'Combining all predictions into a single aggregate obscures whether the engine made correct ID pairings versus whether it made safe auto-resolution decisions. ShaRecon AI reports Proposed-Pair Precision/Recall, Auto-Resolution Precision/Recall, Review-Routing Accuracy, and False-Positive Monetary Exposure separately.',
    targetTab: 'evaluation',
  },
  {
    id: 'integer-paise',
    category: 'Safety',
    question: 'Why does ShaRecon AI use integer-paise arithmetic?',
    answer:
      'Standard JavaScript floating-point numbers introduce IEEE 754 precision drift (e.g. 0.1 + 0.2 = 0.30000000000000004). Enforcing 1 INR = 100 integer paise guarantees zero rounding error across ledger additions, fee deductions, and currency deltas.',
    targetTab: 'methodology',
  },
];

const GLOSSARY_TERMS = [
  {
    term: 'UTR (Unique Transaction Reference)',
    definition: 'A 16-to-22 character alphanumeric identifier generated by Indian banking systems (NEFT/RTGS/IMPS) that uniquely confirms bank account credit.',
  },
  {
    term: 'Nodal / Escrow Account',
    definition: 'A special RBI-mandated intermediary bank account held by payment aggregators (like Razorpay) where customer funds sit before settlement to merchant accounts.',
  },
  {
    term: 'MDR (Merchant Discount Rate)',
    definition: 'The fee percentage charged by payment aggregators per transaction, ranging from 2.0% (standard cards/UPI) to 3.5% (corporate/international).',
  },
  {
    term: 'GST on MDR (18%)',
    definition: 'Indian Goods and Services Tax applied exclusively to the gateway fee component, deducted alongside MDR prior to bank payout.',
  },
  {
    term: 'Paise',
    definition: 'The smallest unit of Indian currency (1 INR = 100 paise). ShaRecon AI stores all financial values as integer paise to prevent floating-point drift.',
  },
  {
    term: 'T+1 / T+2 Settlement',
    definition: 'The time lag (in business days) between customer payment capture (T) and gateway funds credit into the merchant bank account.',
  },
  {
    term: 'Collision Prevention',
    definition: 'An algorithmic constraint solver ensuring no single settlement batch or bank statement credit is double-assigned to multiple payments.',
  },
];

export const HelpTab: React.FC<HelpTabProps> = ({ onNavigateTab, onStartTour }) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState<string>('ALL');
  const [expandedFaqId, setExpandedFaqId] = useState<string | null>('what-is-3way');

  const filteredFaqs = useMemo(() => {
    return FAQ_DATABASE.filter((item) => {
      const matchesCategory = activeCategory === 'ALL' || item.category === activeCategory;
      const matchesSearch =
        !searchQuery ||
        item.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
        item.answer.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesCategory && matchesSearch;
    });
  }, [searchQuery, activeCategory]);

  return (
    <div className="space-y-6">
      {/* Help Hero Banner */}
      <div className="bg-slate-900 text-white rounded-2xl p-6 sm:p-8 shadow-xs relative overflow-hidden">
        <div className="max-w-2xl space-y-3 relative z-10">
          <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full bg-blue-900/80 border border-blue-700/60 text-blue-300 text-xs font-semibold">
            <BookOpen className="w-3.5 h-3.5" />
            <span>Judge Guide &amp; Fintech Onboarding</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">
            How ShaRecon AI Works
          </h2>
          <p className="text-slate-300 text-xs sm:text-sm leading-relaxed">
            ShaRecon AI is an AI Finance Controller prototype designed for the Razorpay AI Buildathon. It reconciles multi-leg transaction streams with integer-paise arithmetic, 4-factor scoring, collision prevention, and grounded Gemini advisory triage.
          </p>
          <div className="flex flex-wrap items-center gap-3 pt-2">
            <button
              onClick={onStartTour}
              className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold flex items-center gap-1.5 transition-colors shadow-xs cursor-pointer"
            >
              <span>Launch 8-Step Demo Tour</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
            <button
              onClick={() => onNavigateTab('methodology')}
              className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 transition-colors cursor-pointer"
            >
              View Architecture &amp; Math
            </button>
          </div>
        </div>
      </div>

      {/* 3-Way Reconciliation Core Primer Card */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <Layers className="w-5 h-5 text-blue-600" />
            The 3-Way Reconciliation Lifecycle
          </h3>
          <span className="text-xs font-semibold text-slate-500 bg-slate-100 px-2.5 py-1 rounded-lg">
            Integer Paise • 4-Factor Scoring
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
          <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-slate-900">Leg 1: Merchant Ledger</span>
              <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-blue-100 text-blue-800">CAPTURE</span>
            </div>
            <p className="text-slate-600 leading-relaxed">
              Customer payment captured via Razorpay checkout. Records Gross Amount (e.g. ₹5,000.00), Payment ID (`pay_0001`), Order Ref (`order_0001`), and timestamp.
            </p>
          </div>

          <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-slate-900">Leg 2: Nodal Settlement</span>
              <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-amber-100 text-amber-800">GATEWAY</span>
            </div>
            <p className="text-slate-600 leading-relaxed">
              Razorpay settles captured funds in payout batches deducting 2.0%-3.5% MDR + 18% GST on fee. Records Net Amount (e.g. ₹4,882.00), Settlement ID, and UTR.
            </p>
          </div>

          <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-slate-900">Leg 3: Bank Account</span>
              <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-100 text-emerald-800">STATEMENT</span>
            </div>
            <p className="text-slate-600 leading-relaxed">
              Merchant bank account credits arriving after T+1/T+2 clearing delay. Records exact credit amount, bank statement UTR (`RBIP100...`), and date.
            </p>
          </div>
        </div>
      </div>

      {/* 4-Factor Scoring Breakdown */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs space-y-4">
        <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
          <Scale className="w-5 h-5 text-violet-600" />
          Deterministic 4-Factor Confidence Scoring (0 - 100 Points)
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 text-xs">
          <div className="border border-slate-200 rounded-xl p-3.5 space-y-1.5 bg-slate-50/50">
            <div className="flex items-center justify-between">
              <span className="font-bold text-slate-800">1. Reference Match</span>
              <span className="font-mono font-bold text-blue-600">40 Pts</span>
            </div>
            <p className="text-slate-600 text-[11px] leading-relaxed">
              Exact payment ID (`40 pts`), order reference (`30 pts`), or sanitized token substring (`20 pts`).
            </p>
          </div>

          <div className="border border-slate-200 rounded-xl p-3.5 space-y-1.5 bg-slate-50/50">
            <div className="flex items-center justify-between">
              <span className="font-bold text-slate-800">2. Amount Match</span>
              <span className="font-mono font-bold text-emerald-600">35 Pts</span>
            </div>
            <p className="text-slate-600 text-[11px] leading-relaxed">
              Net settled vs expected MDR+GST net (`20 pts`) + Bank credit vs settled (`15 pts`) in exact paise.
            </p>
          </div>

          <div className="border border-slate-200 rounded-xl p-3.5 space-y-1.5 bg-slate-50/50">
            <div className="flex items-center justify-between">
              <span className="font-bold text-slate-800">3. Date Proximity</span>
              <span className="font-mono font-bold text-amber-600">15 Pts</span>
            </div>
            <p className="text-slate-600 text-[11px] leading-relaxed">
              T+0 to T+1 calendar proximity (`15 pts`), T+2 (`10 pts`), T+3 (`5 pts`). Negative delta penalized.
            </p>
          </div>

          <div className="border border-slate-200 rounded-xl p-3.5 space-y-1.5 bg-slate-50/50">
            <div className="flex items-center justify-between">
              <span className="font-bold text-slate-800">4. UTR &amp; Description</span>
              <span className="font-mono font-bold text-violet-600">10 Pts</span>
            </div>
            <p className="text-slate-600 text-[11px] leading-relaxed">
              Alphanumeric UTR format validation (`5 pts`) + statement description token overlap (`5 pts`).
            </p>
          </div>
        </div>
      </div>

      {/* Searchable FAQ Section */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
              <HelpCircle className="w-5 h-5 text-blue-600" />
              Frequently Asked Questions
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">
              Clear technical explanations for hackathon evaluators and finance controllers.
            </p>
          </div>

          {/* Search Box */}
          <div className="relative min-w-[240px]">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search concepts, formulas..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-3 py-1.5 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-900 focus:outline-hidden focus:ring-1 focus:ring-blue-500"
            />
          </div>
        </div>

        {/* Category Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1 text-xs">
          {(['ALL', 'Concepts', 'Scoring', 'Safety', 'Metrics', 'AI'] as const).map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-3 py-1 rounded-lg font-semibold transition-colors shrink-0 cursor-pointer ${
                activeCategory === cat
                  ? 'bg-blue-600 text-white'
                  : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
              }`}
            >
              {cat === 'ALL' ? 'All Questions' : cat}
            </button>
          ))}
        </div>

        {/* Accordion FAQ List */}
        <div className="space-y-2.5 pt-2">
          {filteredFaqs.map((faq) => {
            const isExpanded = expandedFaqId === faq.id;

            return (
              <div
                key={faq.id}
                className="border border-slate-200 rounded-xl overflow-hidden transition-colors"
              >
                <button
                  onClick={() => setExpandedFaqId(isExpanded ? null : faq.id)}
                  className="w-full px-4 py-3 text-left flex items-center justify-between gap-3 hover:bg-slate-50 transition-colors cursor-pointer"
                  aria-expanded={isExpanded}
                >
                  <span className="text-xs sm:text-sm font-bold text-slate-900">
                    {faq.question}
                  </span>
                  <div className="flex items-center gap-2 shrink-0">
                    <span className="text-[10px] font-semibold uppercase px-2 py-0.5 rounded bg-slate-100 text-slate-600 font-mono">
                      {faq.category}
                    </span>
                    {isExpanded ? (
                      <ChevronUp className="w-4 h-4 text-slate-400" />
                    ) : (
                      <ChevronDown className="w-4 h-4 text-slate-400" />
                    )}
                  </div>
                </button>

                {isExpanded && (
                  <div className="px-4 pb-3.5 pt-1 text-xs text-slate-600 bg-slate-50/50 border-t border-slate-100 space-y-2 leading-relaxed">
                    <p>{faq.answer}</p>
                    {faq.targetTab && (
                      <button
                        onClick={() => onNavigateTab(faq.targetTab!)}
                        className="text-xs text-blue-600 font-semibold hover:underline inline-flex items-center gap-1 cursor-pointer pt-1"
                      >
                        <span>Open related workspace</span>
                        <ArrowRight className="w-3 h-3" />
                      </button>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Financial Terms Glossary */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs space-y-4">
        <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
          <FileText className="w-5 h-5 text-emerald-600" />
          Fintech &amp; Reconciliation Glossary
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
          {GLOSSARY_TERMS.map((term) => (
            <div
              key={term.term}
              className="bg-slate-50 border border-slate-200/80 rounded-xl p-3.5 space-y-1"
            >
              <span className="font-bold text-slate-900 font-mono text-[11px] block text-blue-900">
                {term.term}
              </span>
              <p className="text-slate-600 leading-relaxed">{term.definition}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Non-Negotiable Safety Disclosures */}
      <div className="bg-amber-50/80 border border-amber-200 rounded-2xl p-5 shadow-xs text-xs text-amber-900 space-y-2">
        <div className="flex items-center gap-2 font-bold text-amber-950">
          <ShieldCheck className="w-4 h-4 text-amber-600 shrink-0" />
          <span>Buildathon Prototype Disclosures &amp; Safety Boundaries</span>
        </div>
        <ul className="list-disc pl-5 space-y-1 text-amber-800 leading-relaxed">
          <li><strong>Synthetic Simulation</strong>: All records, UTRs, and settlements are generated deterministically to model Razorpay fee rules and banking delays.</li>
          <li><strong>No Real Money Movement</strong>: ShaRecon AI is an analytical reconciliation controller and does not initiate bank transfers or payment gateway refunds.</li>
          <li><strong>Advisory AI</strong>: Gemini 2.5 Flash functions strictly as an advisory copilot; core reconciliation logic operates 100% deterministically without external LLM dependencies.</li>
        </ul>
      </div>
    </div>
  );
};
